name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Installing Dependencies
        run: |
        if [ -d 'project' ]; then cd project && npm install; else echo 'Skip. The project directory does not exist'; fi

      - name: Linting
        run: |
        if [ -d 'project' ]; then cd project && npm test && npm run eslint; else echo 'Skip. The project directory does not exist'; fi

      - name: Pre Deploy
        run: |
        if [ -d 'project' ]; then cd project && npm run predeploy; else echo 'Skip. The project directory does not exist'; fi

        - name: Deploy
            run: |
            if [ -d 'project' ]; then cd project && npm run deploy; else echo 'Skip. The project directory does not exist'; fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: ./project/build
          BRANCH: gh-pages
          SINGLE_COMMIT: false
